Create Getting Started page
kubevirt/user-guide pull request #356
Opened 2020-09-14 20:18 UTC by mazzystr

This pull requests creates a Getting Started page in user-guide so that new users and contributors have a nice itinerary of tasks to complete to get up to speed with the project.

2020-09-15 15:26 UTC, codificat commented
An initial comment about scope/goals: 

> ... so that new users and contributors have a nice itinerary of tasks to complete to get up to speed with the project.

You mention _users_ and contributors, but the content of the new page seems to be quite focused on contributors (e.g. the first line is about signing the CNCF CLA, which users certainly don't have to do)

2020-09-15 15:55 UTC, mazzystr commented
> An initial comment about scope/goals:
> 
> > ... so that new users and contributors have a nice itinerary of tasks to complete to get up to speed with the project.
> 
> You mention _users_ and contributors, but the content of the new page seems to be quite focused on contributors.
> 
> Should this be a _Contributing_ page instead of _Getting Started_ ?

No idea...  We already have a Getting Started page [here](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md) and a Contributing page [here](https://github.com/kubevirt/kubevirt/blob/master/CONTRIBUTING.md).

2020-10-20 17:26 UTC, codificat requested changes
Some comments.

Besides that, the Welcome page has a section called _Developer_ which currently points to one of the links contained here (CONTRIBUTING.md). I believe that page should be updated to point to this new section instead.

2020-10-20 17:26 UTC, codificat commented on appendix/contributing.md
> +* You need to be familiar with writing code in golang.  See the [golang tour](https://tour.golang.org/welcome/1) to familiarize yourself.
This is if you want to contribute code... there are other ways to contribute (e.g. documentation, blog posts, raising issues, helping triage/reproduce...).

Maybe worth expanding / clarifying along those lines. You do talk about _other ways to contribute_ below already... point there?

2020-10-20 17:26 UTC, codificat commented on appendix/contributing.md
> +* Check a repository issues list for issues that make good entry points.
Mention the `good-first-issue` label?

2020-10-20 17:26 UTC, codificat commented on appendix/contributing.md
> +* Open a pull request using GitHub to existing documentation.
Maybe it's just me, but I don't really understand this sentence... "to existing documentation"?

2020-11-03 11:17 UTC, codificat commented
This is still pending:

> Besides that, the Welcome page has a section called _Developer_ which currently points to one of the links contained here (CONTRIBUTING.md). I believe that page should be updated to point to this new section instead.

2020-11-03 19:01 UTC, mazzystr commented
> at, the Welcome pag

To me the Welcome page is good enough.  (ref. [KNIECO-2537](https://issues.redhat.com/browse/KNIECO-2537)) We have a request to make a friendly page for incoming developers from IBM.  

Where do we want to go from here?  Update Welcome page with this content?  Update CONTIRBUTING page to point to the Welcome page?  Both those items feel out of scope for the story.

2020-11-17 00:50 UTC, codificat commented
> Where do we want to go from here? Update Welcome page with this content? Update CONTIRBUTING page to point to the Welcome page? Both those items feel out of scope for the story.

I was just suggesting to replace the link in the welcome page that links directly to the CONTRIBUTING page with a link to this new content from this PR (which includes a link to CONTRIBUTING but provides more context).

2020-11-20 17:39 UTC, mazzystr commented
@codificat Contributing link on Welcome page is updated

2020-11-20 20:28 UTC, codificat commented
Ok, thanks.
/lgtm
/approve

2020-11-20 20:29 UTC, codificat approved these changes

2020-11-27 14:37 UTC, fabiand commented
/lgtm
/approve

2020-11-27 14:38 UTC, merged