update node-labeller documentation
kubevirt/user-guide pull request #386
Opened 2021-02-16 12:13 UTC by ksimon1

update node-labeller documentation
/hold 
Merge only after kubevirt PR https://github.com/kubevirt/kubevirt/pull/4916 is merged
Signed-off-by: Karel Simon <ksimon@redhat.com>

2021-02-17 23:56 UTC, mazzystr commented
@ksimon1  We have bad timing on your contribution.  The user-guide migration to mkdocs markdown engine and restructuring the page hierarchy completed today.

Your pull req now needs a rebase.  The rebase will be difficult. `creation/devices.md` has been renamed to `docs/virtual_machines/virtual_hardware.md`.  You will need to integrate this diff into the new file.  Another option is pull master, recreate your branch, recreate the content in the new file, create new pull req.  Yet another option is for me to do it.   The con to that is you don't get the GitHub credit.

I'm happy to discuss further in [slack](https://kubernetes.slack.com/archives/C8ED7RKFE)

2021-02-18 21:36 UTC, mazzystr commented
@@ksimon1 Thanks for going through the rebase journey.  I will remove the `do-not-merge/hold` label and proceed with normal peer review.

2021-02-18 21:52 UTC, mazzystr commented
@ksimon1 just a couple nits from me then +1

2021-02-18 21:53 UTC, mazzystr requested changes

2021-02-18 21:53 UTC, mazzystr commented on docs/virtual_machines/virtual_hardware.md
> +Kubevirt node-labeller creates 3 types of labels: cpu models, cpu features, kvm info.
The last item in a comma separated list get a `, and item`

2021-02-18 21:53 UTC, mazzystr commented on docs/virtual_machines/virtual_hardware.md
> -        minCPU: "Penryn"
Please encapsulate this code block with ` ```console`.  All these bare code blocks have been showing up in lintting.  We need to get that fixed.

2021-03-02 00:39 UTC, mazzystr requested changes
Fix a couple nits, rebase then you've got your lgtm/approve tag :)

2021-03-03 00:31 UTC, mazzystr requested changes
@ksimon1 Fix a couple of nits and rebase then this will be ready for merge.  Thanks

2021-03-03 05:49 UTC, ksimon1 commented
This can't be merged yet. This PR has to be merged before https://github.com/kubevirt/kubevirt/pull/4916

2021-03-15 13:58 UTC, mazzystr commented
@ksimon1 ping.  We're getting close to 30 days in-progress on this pull req.  Are you still wanting to merge this?

2021-03-15 14:05 UTC, ksimon1 commented
@mazzystr definitely. Still waiting for this PR https://github.com/kubevirt/kubevirt/pull/4916 to be merged and then this PR can be merged.

2021-03-15 20:44 UTC, mazzystr commented
@ksimon1  I applied the do-not-merge/hold label.  Can you rebase and fix small items so that this pull req will be ready to go?

2021-03-16 14:56 UTC, mazzystr commented
/assign @mazzystr

On Tue, Mar 16, 2021 at 4:23 AM kubevirt-bot ***@***.***>
wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by:
> To complete the pull request process
> <https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process>,
> please assign *mazzystr*
> You can assign the PR to them by writing /assign @mazzystr in a comment
> when ready.
>
> The full list of commands accepted by this bot can be found here
> <https://go.k8s.io/bot-commands?repo=kubevirt%2Fuser-guide>.
> Needs approval from an approver in each of these files:
>
>    - *OWNERS <https://github.com/kubevirt/user-guide/blob/master/OWNERS>*
>
> Approvers can indicate their approval by writing /approve in a comment
> Approvers can cancel approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubevirt/user-guide/pull/386#issuecomment-800175882>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS5KZ5JAZS5KDVIA2EI5DTTD45TFANCNFSM4XWK7YIQ>
> .
>

2021-03-29 17:08 UTC, ksimon1 commented
/hold cancel
@mazzystr this PR is ready to be merged

2021-03-29 17:29 UTC, mazzystr commented
/approve
/lgtm

2021-03-29 17:30 UTC, merged