Document KubeVirt VMI update automation
kubevirt/user-guide pull request #400
Opened 2021-02-25 20:07 UTC by davidvossel

We have a new feature that coordinates updating VMIs which has landed in kubevirt that will in the upcoming v0.39.0 release. https://github.com/kubevirt/kubevirt/pull/4686

2021-03-02 00:33 UTC, mazzystr requested changes

2021-03-02 00:33 UTC, mazzystr commented on docs/operations/updating_and_deletion.md
> +```
please update to ```console

2021-03-02 00:33 UTC, mazzystr commented on docs/operations/updating_and_deletion.md
> +```
please update to ```console

2021-03-02 00:33 UTC, mazzystr commented on docs/operations/updating_and_deletion.md
> +```
please update to ```console

2021-03-03 00:33 UTC, mazzystr commented
@davidvossel  Fix those nits so they don't show up in lintting and do a rebase then this pr is +1

2021-03-04 21:04 UTC, davidvossel commented
@mazzystr fixed

2021-03-04 21:13 UTC, mazzystr commented
/approve
/lgtm

2021-03-04 21:15 UTC, merged