Use GitHub Action to detect broken markdown links
kubevirt/user-guide pull request #479
Opened 2021-08-29 05:18 UTC by cydu-cloud

Fixed all the existing broken links and also enabled GitHub Action to detect broken markdown links.

Use `` disabled broken external links.

Follow instructions at https://github.com/gaurav-nelson/github-action-markdown-link-check
See https://github.com/cydu-cloud/user-guide/actions/workflows/action.yml for example runs.

2021-09-02 19:19 UTC, mazzystr requested changes

2021-09-02 19:21 UTC, mazzystr commented
@cydu-cloud Thanks so much for this contribution.  This is going to help a lot!

2021-09-02 20:56 UTC, cydu-cloud commented on .github/workflows/action.yml
> +name: Check docs links
SG, removed this file. 

Get this fix in first to fix existing broken links, and then work on the prow integration.

2021-09-02 22:01 UTC, mazzystr commented
/lgtm
/approve

@cydu-cloud Thanks!  I hope you stick around for awhile :)

2021-09-02 22:02 UTC, merged

2021-11-09 17:13 UTC, mazzystr commented
@cydu-cloud Hello, I'm looking for a contact at Google that can help me with authorization in getting Google added to the KubeVirt ADOPTERS file and display a logo on https://kubevirt.io.  Please contact me via the kubevirt-dev mailing list.  Thanks!