Added explantion about connecting to a vm using "virtctl ssh"
kubevirt/user-guide pull request #538
Opened 2022-04-24 14:09 UTC by isaacdorfman

2022-04-24 14:12 UTC, isaacdorfman commented
@dankenigsberg

2022-04-24 17:14 UTC, mazzystr commented
@isaacdorfman  Please rebase and sign your commit.  See https://github.com/kubevirt/user-guide#sign-your-commits

2022-04-24 17:23 UTC, mazzystr requested changes

2022-04-24 17:23 UTC, mazzystr commented on docs/virtual_machines/accessing_virtual_machines.md
> +*Please not that "virtctl ssh" is only supported in up to date versions of virtctl.
Please use an admonition here.  They make important note pop and grab the eye.

Example code : https://github.com/kubevirt/user-guide/blame/main/docs/virtual_machines/startup_scripts.md#L55-L56
Example render : http://kubevirt.io/user-guide/virtual_machines/startup_scripts/

2022-08-03 14:30 UTC, cwilkers commented
@isaacdorfman This PR is awaiting action by you, and has gone stale, are you able to sign your commits and address @mazzystr 's feedback?

2022-10-02 15:35 UTC, closed without merging