Updating latest_release_notes from 0.38.1 to 0.54.0
kubevirt/user-guide pull request #546
Opened 2022-06-14 08:56 UTC by aburdenthehand

Batch updating the latest release notes (from 0.38.1 to 0.54.0) using modified `update_changelog` script.

This is following on from #401, I suppose. Looks like this script is meant to be run on a monthly basis (or match release cadence). Should it be part of the release process?

Signed-off-by: aburdenthehand <aburden@redhat.com>

2022-06-14 14:26 UTC, phoracek requested changes
It is not really "latest" release notes if we keep last year of versions there.

I would suggest we replace it with a link to https://github.com/kubevirt/kubevirt/releases, so we don't have to update this every month

2022-06-14 14:36 UTC, aburdenthehand commented
> It is not really "latest" release notes if we keep last year of versions there.
> 
> I would suggest we replace it with a link to https://github.com/kubevirt/kubevirt/releases, so we don't have to update this every month

That was my first thought as well. However, the benefit of ~mirroring the release notes in the user guide is that it is included in the search bar, and can be easily navigated using the side bar. The github [Find a release](https://github.com/kubevirt/kubevirt/releases) search is significantly poorer imho.

2022-06-14 15:26 UTC, phoracek commented
I see. Then I'd just nag to keep only the release notes for recent versions only. Or change the title of the page.

2022-06-15 14:16 UTC, maiqueb commented
> > It is not really "latest" release notes if we keep last year of versions there.
> > I would suggest we replace it with a link to https://github.com/kubevirt/kubevirt/releases, so we don't have to update this every month
> 
> That was my first thought as well. However, the benefit of ~mirroring the release notes in the user guide is that it is included in the search bar, and can be easily navigated using the side bar. The github [Find a release](https://github.com/kubevirt/kubevirt/releases) search is significantly poorer imho.

I don't know if it's poorer ... If you want release v0.42.0 you just have to input `"v0\.42\.0"` . That gives the `v0.42.0` release. 
Forces you to use quotes and escape the dots but ... It's easy.

2022-06-15 15:28 UTC, maiqueb commented
Digesting both https://github.com/kubevirt/user-guide/pull/546#issuecomment-1156532157 and https://github.com/kubevirt/user-guide/pull/546#issuecomment-1156612607, my vote would go to feature the full release notes, but to change the name (and heading...) of the page.

2022-06-15 16:04 UTC, aburdenthehand commented
Created #547 to detach changing the name and updating the related files from updating the missing release notes.

2022-06-22 14:20 UTC, merged