Update memory dump command with download options
kubevirt/user-guide pull request #630
Opened 2022-12-25 12:05 UTC by ShellyKa13

Signed-off-by: Shelly Kagan <skagan@redhat.com>

2023-01-03 21:36 UTC, cwilkers requested changes
Great feature, thanks for your documentation PR!

I have only minor grammatical edits

2023-01-03 21:36 UTC, cwilkers commented on docs/operations/memory_dump.md
> +By adding `--output` flag the memory will be dumped to the pvc and then downloaded to the given output path.
```suggestion
By adding the `--output` flag, the memory will be dumped to the PVC and then downloaded to the given output path.
```

2023-01-03 21:36 UTC, cwilkers commented on docs/operations/memory_dump.md
> +For downloading the last memory dump from the PVC associated to the VM, without triggering another memory dump use the memory dump donwload command
```suggestion
For downloading the last memory dump from the PVC associated with the VM, without triggering another memory dump, use the memory dump download command.
```

2023-01-03 21:36 UTC, cwilkers commented on docs/operations/memory_dump.md
> +For downloading memory dump from a PVC already removed from the VM association you can use the [virtctl vmexport command](https://github.com/kubevirt/user-guide/blob/main/docs/operations/export_api.m
```suggestion
For downloading a memory dump from a PVC already removed from the VM association you can use the [virtctl vmexport command](https://github.com/kubevirt/user-guide/blob/main/docs/operations/export_api.md)
```

Also, would it make sense to rephrase "removed from the VM association" as "disassociated from the VM" ?

2023-01-04 08:39 UTC, ShellyKa13 commented
@cwilkers thanks for the review, fixed everything according to your suggestions.

2023-01-06 14:22 UTC, cwilkers commented
/approve

2023-01-06 14:23 UTC, merged