VirtualMachinePool Documentation
kubevirt/user-guide pull request #646
Opened 2023-02-10 13:53 UTC by feitnomore

This PR adds VirtualMachinePool basic details to the KubeVirt user guide.

Signed-off-by: Marcelo Feitoza Parisi <marcelo@feitoza.com.br>

2023-02-10 13:54 UTC, feitnomore commented
Probably it's worth waiting 0.59 release to merge it, as there are some steps that will only work on that version.

2023-02-10 15:26 UTC, cwilkers commented
Thanks for the PR @feitnomore !
/ok-to-test

2023-02-10 23:57 UTC, cwilkers requested changes
Great feature! I've added a few grammatical corrections to improve readability, feel free to accept or modify as you see fit.

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +number of VirtualMachine replicas and its respectives
```suggestion
number of VirtualMachine replicas and their respective
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +VirtualMachineInstances are in ready state at any time.
```suggestion
VirtualMachineInstances are in the ready state at any time.
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +of VirtualMachineInstance replicas which are up are given.
```suggestion
No state is kept and no guarantees are made about the maximum number
of VirtualMachineInstance replicas running at any time.
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +controller will simply do nothing except from logging an error. The user
```suggestion
controller will simply do nothing except log an error. The user
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +*VirtualMachinePools* which conflict with the selector and
```suggestion
is responsible for avoiding the creation of other virtual machines or
*VirtualMachinePools* which may conflict with the selector and
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +VirtualMachinePool is part of Kubevirt API `pool.kubevirt.io/v1alpha1`.
```suggestion
VirtualMachinePool is part of the Kubevirt API `pool.kubevirt.io/v1alpha1`.
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +A VirtualMachinePool could be exposed as a service. When
```suggestion
A VirtualMachinePool may be exposed as a service. When
```

Adjusting tense.

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +persistent storage getting created for each VM within a VMPool. The `DataVolumeTemplate`
```suggestion
Usage of a `DataVolumeTemplates` within a `spec.virtualMachineTemplate.spec` will result in the creation
of unique persistent storage for each VM within a VMPool. The `DataVolumeTemplate`
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +name will have the VM's sequential postfix appended to when the VM is created from the
```suggestion
name will have the VM's sequential postfix appended to it when the VM is created from the
```

2023-02-10 23:57 UTC, cwilkers commented on docs/virtual_machines/pool.md
> +`spec.virtualMachineTemplate.spec.dataVolumeTemplates` which makes each VM a completely unique stateful workload.
```suggestion
`spec.virtualMachineTemplate.spec.dataVolumeTemplates`. This makes each VM a completely unique stateful workload.
```

2023-02-11 01:13 UTC, feitnomore commented
@cwilkers thanks for helping me on this one. I've accepted the suggested changes.

2023-02-13 13:36 UTC, cwilkers commented
Hi @feitnomore , This is a bit of an annoyance, but if you accepted changes through the GitHub interface, then it does not sign off on those commits, which triggers our blocking DCO check.

You can pull the current branch state on your local copy, and squash all your commits, making sure to leave the Signed off by... line intact in the comment.

2023-03-06 19:12 UTC, feitnomore commented
Sorry, I think I forgot to request the review again on this one @cwilkers .

2023-03-06 23:26 UTC, cwilkers commented
Thanks for the bump, I missed the DCO fix when it went in.

/approve
/lgtm

2023-03-06 23:28 UTC, merged