feat(virtctl): Add documentation for the virtctl create vm command
kubevirt/user-guide pull request #648
Opened 2023-02-16 15:00 UTC by 0xFelix

This adds documentation for the virtctl create vm command.

2023-02-17 09:58 UTC, lyarwood requested changes

2023-02-17 09:58 UTC, lyarwood commented on docs/virtual_machines/creating_vms.md
> +manifests from the command line. It leverages instance types and preferences
nit - link?

2023-02-17 09:58 UTC, lyarwood commented on docs/virtual_machines/creating_vms.md
> +To infer instance types and/or preferences from the volume used to boot the
nit - if it lands before this link to https://github.com/kubevirt/user-guide/pull/629/commits/2ca15b6a3bfc4dfbde76b01048c76ca9b4641ceb

2023-02-17 09:58 UTC, lyarwood commented on docs/virtual_machines/creating_vms.md
> +```
Would a numbered list be better here?

2023-02-20 09:38 UTC, lyarwood requested changes
Looking good, could you also add an example piping the definition into `kubectl apply -f` just to make it obvious to users?

2023-02-20 09:38 UTC, lyarwood commented on docs/virtual_machines/creating_vms.md
> +KubeVirt derive those from the volume used to boot the virtual machine.
While derive is valid I'd use the same term as the flag here, infer.

2023-02-20 09:38 UTC, lyarwood commented on docs/virtual_machines/creating_vms.md
> +1. Containerdisk
Mixed case, can you capitalise?

2023-02-20 14:45 UTC, 0xFelix commented
@lyarwood Addressed your comments.

2023-02-20 14:45 UTC, lyarwood commented
/lgtm

2023-02-20 15:42 UTC, jean-edouard reviewed
/approve

2023-02-20 15:51 UTC, merged