chore: update tekton tasks section
kubevirt/user-guide pull request #700
Opened 2023-07-13 09:54 UTC by ksimon1

chore: update tekton tasks section
this PR updates links and mentions about TTO (which is deprecated) and replace them with SSP operator

2023-07-14 08:50 UTC, jcanocan reviewed
Thanks for taking the time to update the documentation. Nice job! I've added a couple of comments. Hope you find them useful :)

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
> +- [Windows customize](https://github.com/kubevirt/ssp-operator/blob/main/data/tekton-pipelines/windows-customize-pipeline.yaml) - Pipeline will install sql server or vs code in windows VM. More infor
```suggestion
- [Windows customize](https://github.com/kubevirt/ssp-operator/blob/main/data/tekton-pipelines/windows-customize-pipeline.yaml) - Pipeline will install SQL server or VS Code in a Windows VM. More informations about pipeline can be found [here](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/examples/pipelines/windows-customize)
```

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
>  The user has to enable `deployTektonTaskResources` feature gate in HCO CR to deploy all its resources
```suggestion
The user has to enable `deployTektonTaskResources` feature gate in HCO CR to deploy all its resources:
```

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
>      TTO requires [Tekton](https://tekton.dev/) to work.
```suggestion
> **Note:** SSP requires [Tekton](https://tekton.dev/) to work.
```

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
> +    SSP does not deploy KubeVirt Tekton tasks resources by default.
Same as above.

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
> +or in SSP CR if SSP is deployed as a stand-alone without HCO
```suggestion
or in SSP CR if SSP is deployed as a stand-alone without HCO:
```

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
> +or in SSP CR if SSP is deployed as a stand-alone without HCO
Same in line https://github.com/kubevirt/user-guide/pull/700/files#diff-a77db169553e543ddbc385a4516c88ce5fd572e287ff4df352928f33eafba3ddR48: 
"User can use this command to enable `deployTektonTaskResources` feature gate in HCO CR", add semicolum.

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
>  TTO is creating multiple example pipelines, e.g.:
```suggestion
SSP is creating multiple example pipelines, e.g.:
```
I'm not sure about this one. Please ignore if it's not accurate.

2023-07-14 08:50 UTC, jcanocan commented on docs/virtual_machines/tekton_tasks.md
>  or in TTO CR:
```suggestion
or in SSP CR:
```

2023-07-18 09:21 UTC, jcanocan commented
Looks good to me! Thanks @ksimon1!

2023-07-20 09:42 UTC, ksimon1 commented
@dhiller, @phoracek can you please review this PR?

2023-07-20 10:12 UTC, dhiller reviewed
/approve

2023-07-26 08:48 UTC, phoracek requested changes

2023-07-26 08:48 UTC, phoracek commented on docs/virtual_machines/tekton_tasks.md
> +**Note:** SSP does not deploy KubeVirt Tekton tasks resources by default.
```suggestion
SSP does not deploy KubeVirt Tekton tasks resources by default.
```

You say that it is not deployed by default and then you document how to opt-in. No need for a note.

2023-07-26 08:48 UTC, phoracek commented on docs/virtual_machines/tekton_tasks.md
> +or in SSP CR if SSP is deployed as a stand-alone without HCO:
```suggestion
or by applying a patch on an existing SSP CR:
```

2023-07-26 08:48 UTC, phoracek commented on docs/virtual_machines/tekton_tasks.md
> +Once `spec.featureGates.deployTektonTaskResources` is set to `true`, SSP will not delete any tasks or pipeline examples even if it is reverted back to false.
```suggestion
**Note:** Once `spec.featureGates.deployTektonTaskResources` is set to `true`, SSP will not delete any tasks or pipeline examples even if it is reverted back to false.
```

2023-07-31 11:29 UTC, phoracek approved these changes
/lgtm
/approve

2023-07-31 11:30 UTC, merged