virtiofs: adds non-privileged virtiofsd sharing
kubevirt/user-guide pull request #734
Opened 2023-11-14 15:56 UTC by jcanocan

It explains how to enable and disable PVC privileged and non-privileged sharing modes thought virtiofsd. It also explains the limitations of each mode.

Feature added in: https://github.com/kubevirt/kubevirt/pull/10657

2024-01-22 12:30 UTC, xpivarc commented
@jcanocan ping

2024-01-23 15:02 UTC, cwilkers requested changes
Just some minor readability changes, but looks good otherwise

2024-01-23 15:02 UTC, cwilkers commented on docs/virtual_machines/disks_and_volumes.md
> +- The virtiofsd daemon (i.e., the daemon in charge to share the PVC with the VM) will run with the QEMU UID/GID (107),
```suggestion
- The virtiofsd daemon (the daemon in charge of sharing the PVC with the VM) will run with the QEMU UID/GID (107),
```

2024-01-23 15:09 UTC, jcanocan commented on docs/virtual_machines/disks_and_volumes.md
> +administration privileges for creating the VM. However, it has some limitation:
Done.

2024-01-23 15:09 UTC, jcanocan commented on docs/virtual_machines/disks_and_volumes.md
> +- The virtiofsd daemon (i.e., the daemon in charge to share the PVC with the VM) will run with the QEMU UID/GID (107),
Done.

2024-01-23 15:48 UTC, cwilkers approved these changes
/approve

2024-01-23 15:50 UTC, merged